//BASICALLY ISME HUM GLOBAL SCOPE AUR BLOCK SCOPE KE BAARE ME DEKHENGE
//{}-> YE WSALA JO CURLY BRACKET HAI AGAR SIRF CURLY BRACKET KE ANDAR KUCH LIKHA H TO WO OBJECT AUR AGAR 
// KISI FUNCTION YA VARIABLE YA LOOP KE CURLY BRACKET ME KUCH LIKHA H TO WO SCOPE
var c = 300
let a = 300
if(true){
    let a = 10
    const b = 20
    var c = 30
console.log("INNER:", a)
}
 console.log(a);
 //console.log(b);
 console.log(c);
//VAR C GLOBALLY 300 DECLARED HAI AUR LOOP KE BAHAR PRINT KRNA EKE BAAD BHI LOOP KE ANDAR KA AA RAH H YAHI VAR KI PROB H ISLIYE VAR KAM USE KRTE HAI
//LET A WALA GLOBALLY DECL AND INITIALIZED HAI TO LOOP KE BAHAR JAB A KO PRINT KRA TO BAHAR WALA HIPRINT HOGA AS VO GLOBAL HAI AS VO LOOP K BAHAR H 
//LOOP KE ANDAR WALA A SIRF LOOP KE ANDAR HI ACCESS YA PRINT HO SAKTA HAI IN SHORT
//SAME GOES FOR B,C